apiVersion: v1
kind: Service
metadata:
  labels:
    run: library-ui
  name: library-ui
  resourceVersion: "80738"
spec:
  ports:
  - nodePort: 30832
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: library-ui
  sessionAffinity: None
  type: LoadBalancer
#status:
  #loadBalancer: {}
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: library-ui
  name: library-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: library-ui
    spec:
      containers:
      - image: registry.eu-de.bluemix.net/feggers/library-ui:v1
        #image: library-ui:v1
        name: library-ui
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        #- name: LIBRARY_URI
        #  value: http://192.168.99.101:30190/library-server-java/api
        - name: APP_URL
        #make sure protocol in server.js (l.194) for library-server Service is adjusted (http or https)
          #value: http://192.168.99.101:30832 #port like service nodeport  #http://localhost:8080
          value: http://159.122.69.136:30832
        - name: CLIENT_ID
          value: a97ad597-4243-4751-9eb8-6e01349d7129
        - name: CONVERSATION_PASSWORD
          value: wxBQBlyqhSds
        - name: CONVERSATION_USERNAME
          value: b1f2a49b-eea7-44c3-ac02-aaa2c7a72cf4
        - name: OAUTH_SERVER_URL
          value: https://appid-oauth.eu-gb.bluemix.net/oauth/v3/e6d2f573-5890-45aa-b82c-dcbb217e6abe
        - name: SECRET
          value: Yjk3MGUzZTktZDcwOS00MmVmLTg2ZTQtNzQ0MjlmOGI2ODYw
        - name: TENANT_ID
          value: e6d2f573-5890-45aa-b82c-dcbb217e6abe
        - name: conv_workspaceid
          value: 1ec4b7df-07d8-4fca-9e79-909409b6d718
        - name: inContainer
          value: "1" # should be set to "1"
        - name: tts_password
          value: GdyGnvvfiWoz
        - name: tts_username
          value: 7907de85-3ca4-42c7-9988-1f0cd28a653a
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
