apiVersion: v1
kind: Service
metadata:
  labels:
    run: library-server
  name: library-server
  #resourceVersion: "78830"
spec:
  ports:
  - nodePort: 30190
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    run: library-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: library-server
  name: library-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: library-server
    spec:
      containers:
      - image: library-server:v3
        name: library-server
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      #schedulerName: default-scheduler
      #securityContext: {}
