apiVersion: v1
kind: Service
metadata:
  labels:
    run: library-ui
  name: library-ui
  resourceVersion: "80738"
spec:
  ports:
  - nodePort: 30832
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: library-ui
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: library-ui
  name: library-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: library-ui
    spec:
      containers:
      - image: library-ui:v3
        name: library-ui
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
